# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='crystal_symmetry',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
