# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0002_auto_20170215_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='img_caption',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
